export const HERO = {
  STANDING: {
    UP: [{ frameCoord: "4x0" }],
    UPRIGHT: [{ frameCoord: "4x4" }],
    RIGHT: [{ frameCoord: "2x4" }],
    DOWNRIGHT: [{ frameCoord: "0x4" }],
    DOWN: [{ frameCoord: "0x0" }],
    DOWNLEFT: [{ frameCoord: "0x2" }],
    LEFT: [{ frameCoord: "2x2" }],
    UPLEFT: [{ frameCoord: "4x2" }],
  },
  MOTION: {
    UP: [
      { frameCoord: "0x22" },
      { frameCoord: "2x22" },
      { frameCoord: "4x22" },
      { frameCoord: "0x24" },
      { frameCoord: "2x24" },
      { frameCoord: "4x24" },
    ],
    UPRIGHT: [
      { frameCoord: "0x18", reverse: true },
      { frameCoord: "2x18", reverse: true },
      { frameCoord: "4x18", reverse: true },
      { frameCoord: "0x20", reverse: true },
      { frameCoord: "2x20", reverse: true },
      { frameCoord: "4x20", reverse: true },
    ],
    RIGHT: [
      { frameCoord: "0x14", reverse: true },
      { frameCoord: "2x14", reverse: true },
      { frameCoord: "4x14", reverse: true },
      { frameCoord: "0x16", reverse: true },
      { frameCoord: "2x16", reverse: true },
      { frameCoord: "4x16", reverse: true },
    ],
    DOWNRIGHT: [
      { frameCoord: "0x10", reverse: true },
      { frameCoord: "0x10", reverse: true },
      { frameCoord: "2x10", reverse: true },
      { frameCoord: "2x10", reverse: true },
      { frameCoord: "4x10", reverse: true },
      { frameCoord: "4x10", reverse: true },
      { frameCoord: "0x14", reverse: true },
      { frameCoord: "0x14", reverse: true },
      { frameCoord: "2x14", reverse: true },
      { frameCoord: "2x14", reverse: true },
      { frameCoord: "4x14", reverse: true },
      { frameCoord: "4x14", reverse: true },
    ],
    DOWN: [
      { frameCoord: "2x6" },
      { frameCoord: "0x6" },
      { frameCoord: "4x6" },
      { frameCoord: "0x8" },
      { frameCoord: "2x8" },
      { frameCoord: "4x8" },
    ],
    DOWNLEFT: [
      { frameCoord: "0x10" },
      { frameCoord: "2x10" },
      { frameCoord: "4x10" },
      { frameCoord: "0x14" },
      { frameCoord: "2x14" },
      { frameCoord: "4x14" },
    ],
    LEFT: [
      { frameCoord: "0x14" },
      { frameCoord: "2x14" },
      { frameCoord: "4x14" },
      { frameCoord: "0x16" },
      { frameCoord: "2x16" },
      { frameCoord: "4x16" },
    ],
    UPLEFT: [
      { frameCoord: "0x18" },
      { frameCoord: "2x18" },
      { frameCoord: "4x18" },
      { frameCoord: "0x20" },
      { frameCoord: "2x20" },
      { frameCoord: "4x20" },
    ],
  },
  STARTING: [{ frameCoord: "0x2" }],
};

export const GAME_OBJECTS = {
  seat: [{ frameCoord: "6x5", size: 32, active: false }],
  desk: [
    { frameCoord: "6x0", size: 48, active: false },
    { frameCoord: "8x0", size: 48, active: false },
  ],
  computer: [
    { frameCoord: "6x3", size: 32, active: false },
    { frameCoord: "8x3", size: 32, active: true },
    { frameCoord: "10x3", size: 32, active: false },
  ],
  blueprint: [
    { frameCoord: "8x5", size: 32, active: false },
    { frameCoord: "9x5", size: 32, active: false },
  ],
  mona: [{ frameCoord: "2x0", size: 32, active: true }],
};
